services:

  dotnetapi.webapi:
    image: dotnetapi.webapi
    build:
      context: .
      dockerfile: DotnetApi.WebApi/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      # Optionally inject the connection string explicitly (replace 'DefaultConnection' with your actual key):
      # - ConnectionStrings__DefaultConnection=Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword;
      - ConnectionStrings__DefaultConnection=User Id=postgres.iqycdvnkmygdhshdwdkv;Password=bobbyFeelingFine3002;Server=aws-1-eu-west-1.pooler.supabase.com;Port=5432;Database=postgres
