runtime: python310
service: default

# Blazor WASM is static files. We can serve them via a simple handler.
handlers:
- url: /
  static_files: WebApi/wwwroot/index.html
  upload: WebApi/wwwroot/index.html
- url: /(.*)
  static_files: WebApi/wwwroot/\1
  upload: WebApi/wwwroot/(.*)
